### ISSUE TITLE
How to invoke locally?

### ISSUE THREAD

**Issue by newbreedofgeek** [AnomalyInnovations/serverless-es7#1]
Hello,

I'm testing this starter kit as I'd like to add async await support my my lambdas.

I primarily would like to invoke this locally.

`But when I run "serverless invoke local --function hello"`

I get the error:
```
(function (exports, require, module, __filename, __dirname) { export const hello = async (event, context, callback) => {
                                                              ^^^^^^
SyntaxError: Unexpected token export....
.....
```

Which basically means its not been transpiled by babel.

How can I invoke locally?

Thanks,

**Comment by jayair** [comment]
Hmm that is weird. What version of serverless are you using?

**Comment by andrewoh531** [comment]
You've left out `webpack`  in your command.

e.g. you need to run `serverless webpack invoke local --function hello`

**Comment by newbreedofgeek** [comment]
@andrewoh531 when I run ` serverless webpack invoke local --function hello` I get `Command "webpack invoke local" not found, Run "serverless`  so that does not work.

@jayair I'm using serverless version 1.8.0

**Comment by jayair** [comment]
@newbreedofgeek Can I see the full error?

**Comment by newbreedofgeek** [comment]
@jayair there is not much error detail, when I run `serverless webpack invoke local --function hello`

I get:

```
  Serverless Error ---------------------------------------
 
     Command "webpack invoke local" not found, Run "serverless
     help" for a list of all available commands.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.10.3
     Serverless Version: 1.8.0

```

I have not made any changes after I cloned this project, I just clones it, ran `npm install` and then ran the above command. If I run `serverless webpack invoke --function hello` it works, but `local` does not work. 

Actually what is the difference between the `invoke` and `invoke local`

**Comment by fwang** [comment]
Hi @newbreedofgeek, sorry for the confusion. Let me explain what the following commands do:
```
serverless invoke
serverless invoke local
serverless webpack invoke
```
The first 2 are built-in commands of Serverless Framework. The former `serverless invoke` runs your Lambda function remotely and `serverless invoke local` runs it locally.
```
(function (exports, require, module, __filename, __dirname) { export const hello = async (event, context, callback) => {
                                                              ^^^^^^
SyntaxError: Unexpected token export....
.....
```
The reason you got the error earlier when you ran `serverless invoke local --function hello` was because Serverless Framework tried to run your Lambda function in es7 syntax without transpiling first. This is the expected behavior.

The tutorial uses this Serverless Framework plugin, [serverless-webpack](https://github.com/elastic-coders/serverless-webpack) to handle transpile. The third command `serverless webpack invoke` is added on by the plugin. It will transpile the Lambda function, then invoke it locally. And `serverless webpack invoke local` is not a valid command.

**Comment by newbreedofgeek** [comment]
@fwang great! tnx :)
